Reversing Radar Project: leds.c File Reference
leds.c File Reference
Receiver Node
LED control implementation for distance indication.
Functions
void leds_7 ()
Turn on all LEDs (pattern 7) – closest distance.
void leds_6 ()
Turn on LEDs pattern 6.
void leds_5 ()
Turn on LEDs pattern 5.
void leds_4 ()
Turn on LEDs pattern 4.
void leds_3 ()
Turn on LEDs pattern 3.
void leds_2 ()
Turn on LEDs pattern 2.
void leds_1 ()
Turn on LEDs pattern 1 – only Green1 for farthest distance.
Detailed Description
LED control implementation for distance indication.
Each function corresponds to a specific LED pattern, representing different distance thresholds from the CAN receiver.
Function Documentation
leds_1()
void leds_1 (void)
Turn on LEDs pattern 1 – only Green1 for farthest distance.
Turn on LED pattern 1 (closest distance indication).
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().
leds_2()
void leds_2 (void)
Turn on LEDs pattern 2.
Turn on LED pattern 2.
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().
leds_3()
void leds_3 (void)
Turn on LEDs pattern 3.
Turn on LED pattern 3.
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().
leds_4()
void leds_4 (void)
Turn on LEDs pattern 4.
Turn on LED pattern 4.
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().
leds_5()
void leds_5 (void)
Turn on LEDs pattern 5.
Turn on LED pattern 5.
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().
leds_6()
void leds_6 (void)
Turn on LEDs pattern 6.
Turn on LED pattern 6.
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().
leds_7()
void leds_7 (void)
Turn on all LEDs (pattern 7) – closest distance.
Turn on LED pattern 7 (all LEDs on for very close distance).
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().