Reversing Radar Project: leds.h File Reference
leds.h File Reference
Receiver Node
LED control functions for the distance indicator.
Functions
void leds_1 (void)
Turn on LED pattern 1 (closest distance indication).
void leds_2 (void)
Turn on LED pattern 2.
void leds_3 (void)
Turn on LED pattern 3.
void leds_4 (void)
Turn on LED pattern 4.
void leds_5 (void)
Turn on LED pattern 5.
void leds_6 (void)
Turn on LED pattern 6.
void leds_7 (void)
Turn on LED pattern 7 (all LEDs on for very close distance).
Detailed Description
LED control functions for the distance indicator.
This module provides functions to turn on a specific number of LEDs according to the measured distance from the CAN receiver node.
Function Documentation
leds_1()
void leds_1 (void)
Turn on LED pattern 1 (closest distance indication).
Turn on LED pattern 1 (closest distance indication).
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().
leds_2()
void leds_2 (void)
Turn on LED pattern 2.
Turn on LED pattern 2.
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().
leds_3()
void leds_3 (void)
Turn on LED pattern 3.
Turn on LED pattern 3.
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().
leds_4()
void leds_4 (void)
Turn on LED pattern 4.
Turn on LED pattern 4.
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().
leds_5()
void leds_5 (void)
Turn on LED pattern 5.
Turn on LED pattern 5.
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().
leds_6()
void leds_6 (void)
Turn on LED pattern 6.
Turn on LED pattern 6.
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().
leds_7()
void leds_7 (void)
Turn on LED pattern 7 (all LEDs on for very close distance).
Turn on LED pattern 7 (all LEDs on for very close distance).
References Blue1_Pin, Blue2_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by StartDefaultTask().