Reversing Radar Project: main.c File Reference
main.c File Reference
Functions
void SystemClock_Config (void)
System Clock Configuration.
static void MX_GPIO_Init (void)
GPIO Initialization Function.
static void MX_CAN_Init (void)
CAN Initialization Function.
static void MX_USART2_UART_Init (void)
USART2 Initialization Function.
void HAL_CAN_RxFifo0MsgPendingCallback (CAN_HandleTypeDef *hcan)
CAN RX FIFO 0 message pending callback.
int main (void)
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef *htim)
Period elapsed callback in non blocking mode.
void Error_Handler (void)
This function is executed in case of error occurrence.
Variables
CAN_HandleTypeDef hcan
UART_HandleTypeDef huart2
osThreadId_t defaultTaskHandle
osThreadId_t serialTaskHandle
osThreadId_t buzzerTaskHandle
osThreadId_t lcdTaskHandle
float Distance
int time = 500
char Buffer [8]
char lcdBuffer [8]
uint8_t RxData [8]
uint32_t TxMailbox
uint8_t digit1
uint8_t digit2
CAN_TxHeaderTypeDef TxHeader
CAN_RxHeaderTypeDef RxHeader
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Handles unrecoverable application errors.
Handles HAL errors.
Return values
None
Referenced by MX_CAN_Init(), MX_USART2_UART_Init(), and SystemClock_Config().
HAL_CAN_RxFifo0MsgPendingCallback()
void HAL_CAN_RxFifo0MsgPendingCallback (CAN_HandleTypeDef * hcan)
CAN RX FIFO 0 message pending callback.
Note
This callback is invoked by the HAL when a CAN message is received in FIFO0. The received frame is read and stored in the RX buffer. In case of reception error, an error indicator LED is activated.
Parameters
hcan Pointer to the CAN handle.
Return values
None
References hcan, RxData, and RxHeader.
HAL_TIM_PeriodElapsedCallback()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * htim)
Period elapsed callback in non blocking mode.
Note
This function is called when TIM2 interrupt took place, inside HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment a global variable "uwTick" used as application time base.
Parameters
htim : TIM handle
Return values
None
main()
int main (void)
References buzzerTask_init(), buzzerTaskHandle, defaultTaskHandle, hcan, lcdTask_init(), lcdTaskHandle, MX_CAN_Init(), MX_GPIO_Init(), MX_USART2_UART_Init(), serialTask_init(), serialTaskHandle, StartDefaultTask(), and SystemClock_Config().
MX_CAN_Init()
void MX_CAN_Init (void) static
CAN Initialization Function.
Parameters
None
Return values
None
Configure CAN filter for receiving messages
This block sets up the CAN filter to accept messages from the transmitter node with ID 0x103. Only messages matching this ID will trigger the RX FIFO0 message pending callback.
< Standard CAN frame
< Data frame
< STM32F103 transmitter ID
< Filter bank index
< Filter for ID 0x103
< Mask for ID 0x103
< Number of filters for master CAN
References canfilterconfig, Error_Handler(), hcan, and TxHeader.
Referenced by main().
MX_GPIO_Init()
void MX_GPIO_Init (void) static
GPIO Initialization Function.
Parameters
None
Return values
None
References A_Pin, B_Pin, Blue1_Pin, Blue2_Pin, Buzzer_Pin, C_Pin, D_Pin, DIG1_Pin, DIG2_Pin, DP_Pin, E_Pin, F_Pin, G_Pin, Green1_Pin, Green2_Pin, Green3_Pin, Red1_Pin, and Red2_Pin.
Referenced by main().
MX_USART2_UART_Init()
void MX_USART2_UART_Init (void) static
USART2 Initialization Function.
Parameters
None
Return values
None
References Error_Handler(), and huart2.
Referenced by main().
SystemClock_Config()
void SystemClock_Config (void)
System Clock Configuration.
Configures the system clock.
Return values
None
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Initializes the CPU, AHB and APB buses clocks
References Error_Handler().
Referenced by main().
Variable Documentation
Buffer
char Buffer[8]
UART transmission buffer
Referenced by serialTask_init().
buzzerTaskHandle
osThreadId_t buzzerTaskHandle
Handle for the buzzer control task
Referenced by main().
defaultTaskHandle
osThreadId_t defaultTaskHandle
Handle for the default system task
Referenced by main().
digit1
uint8_t digit1
First displayed digit
Referenced by lcdTask_init().
digit2
uint8_t digit2
Second displayed digit
Referenced by lcdTask_init().
Distance
float Distance
Distance value computed from received CAN data (meters)
Referenced by buzzerTask_init(), lcdTask_init(), serialTask_init(), and StartDefaultTask().
hcan
CAN_HandleTypeDef hcan
CAN handle
Referenced by HAL_CAN_RxFifo0MsgPendingCallback(), main(), MX_CAN_Init(), MX_CAN_Init(), and TxTask_init().
huart2
UART_HandleTypeDef huart2
UART2 handle
Referenced by MX_USART2_UART_Init(), MX_USART2_UART_Init(), and serialTask_init().
lcdBuffer
char lcdBuffer[8]
LCD/7-segment buffer
lcdTaskHandle
osThreadId_t lcdTaskHandle
Handle for the LCD display task
Referenced by main().
RxData
uint8_t RxData[8]
CAN received data buffer
Referenced by HAL_CAN_RxFifo0MsgPendingCallback(), lcdTask_init(), and StartDefaultTask().
RxHeader
CAN_RxHeaderTypeDef RxHeader
Referenced by HAL_CAN_RxFifo0MsgPendingCallback().
serialTaskHandle
osThreadId_t serialTaskHandle
Handle for the UART serial communication task
Referenced by main().
time
int time = 500
Buzzer timing variable (ms)
Referenced by buzzerTask_init(), and StartDefaultTask().
TxHeader
CAN_TxHeaderTypeDef TxHeader
CAN transmit header
Referenced by MX_CAN_Init(), MX_CAN_Init(), and TxTask_init().
TxMailbox
uint32_t TxMailbox
CAN transmit mailbox index
CAN mailbox index
Referenced by TxTask_init().