Reversing Radar Project: app_tasks.h File Reference
app_tasks.h File Reference
Receiver Node
FreeRTOS task declarations for the CAN receiver application.
Functions
void StartDefaultTask (void *argument)
Default FreeRTOS task.
void serialTask_init (void *argument)
UART serial communication task.
void buzzerTask_init (void *argument)
Buzzer control task.
void lcdTask_init (void *argument)
LCD display task.
Variables
osThreadId_t defaultTaskHandle
osThreadId_t serialTaskHandle
osThreadId_t buzzerTaskHandle
osThreadId_t lcdTaskHandle
Detailed Description
FreeRTOS task declarations for the CAN receiver application.
This file contains the task handles and task function prototypes used by the receiver node. Each task is created in main.c and executed under the FreeRTOS scheduler.
Function Documentation
buzzerTask_init()
void buzzerTask_init (void * argument)
Buzzer control task.
Controls the buzzer behavior based on application events.
Parameters
argument Pointer passed to the task (not used).
Controls the buzzer behavior based on the measured distance. The buzzer toggles faster as the distance decreases.
Parameters
argument Pointer passed to the task (not used).
References Buzzer_Pin, Distance, and time.
Referenced by main().
lcdTask_init()
void lcdTask_init (void * argument)
LCD display task.
Updates the LCD or display elements based on received CAN data.
Parameters
argument Pointer passed to the task (not used).
LCD display task.
Displays the shortest received distance on a multiplexed 2-digit 7-segment display. If the distance exceeds the maximum threshold, a warning pattern is shown.
Parameters
argument Pointer passed to the task (not used).
References DIG1_HIGH, DIG1_LOW, DIG2_HIGH, DIG2_LOW, digit1, digit2, Distance, DP_OFF, DP_ON, RxData, and SevenSegment_Update().
Referenced by main().
serialTask_init()
void serialTask_init (void * argument)
UART serial communication task.
Handles serial data transmission and/or reception over UART.
Parameters
argument Pointer passed to the task (not used).
UART serial communication task.
Periodically transmits the measured distance value via UART for debugging or monitoring purposes.
Parameters
argument Pointer passed to the task (not used).
References Buffer, Distance, and huart2.
Referenced by main().
StartDefaultTask()
void StartDefaultTask (void * argument)
Default FreeRTOS task.
This task typically runs background or system-level operations.
Parameters
argument Pointer passed to the task (not used).
Default FreeRTOS task.
This task selects the shortest distance received via CAN and updates LED patterns accordingly. It also updates the buzzer timing variable.
Parameters
argument Pointer passed to the task (not used).
References Distance, leds_1(), leds_2(), leds_3(), leds_4(), leds_5(), leds_6(), leds_7(), RxData, and time.
Referenced by main().
Variable Documentation
buzzerTaskHandle
osThreadId_t buzzerTaskHandle extern
Handle for the buzzer control task
Referenced by main().
defaultTaskHandle
osThreadId_t defaultTaskHandle extern
Handle for the default system task
Referenced by main().
lcdTaskHandle
osThreadId_t lcdTaskHandle extern
Handle for the LCD display task
Referenced by main().
serialTaskHandle
osThreadId_t serialTaskHandle extern
Handle for the UART serial communication task
Referenced by main().