Reversing Radar Project: app_tasks.c File Reference
app_tasks.c File Reference
Receiver Node
FreeRTOS task implementations for the CAN receiver node.
Macros
#define DIG1_HIGH()
#define DIG1_LOW()
#define DIG2_HIGH()
#define DIG2_LOW()
#define DP_ON()
#define DP_OFF()
Functions
void StartDefaultTask (void *argument)
Default task handling LED indication logic.
void serialTask_init (void *argument)
UART serial output task.
void buzzerTask_init (void *argument)
Buzzer control task.
void lcdTask_init (void *argument)
7-segment display task.
Variables
float Distance
int time
uint8_t RxData [8]
uint8_t digit1
uint8_t digit2
char Buffer [8]
char lcdBuffer [8]
Detailed Description
FreeRTOS task implementations for the CAN receiver node.
This file contains all FreeRTOS task functions used by the receiver node. Tasks handle LED indication, UART output, buzzer control, and 7-segment display updates based on received CAN distance data.
Macro Definition Documentation
DIG1_HIGH
#define DIG1_HIGH ()
Value:
HAL_GPIO_WritePin(GPIOB, DIG1_Pin, GPIO_PIN_SET)
Referenced by lcdTask_init().
DIG1_LOW
#define DIG1_LOW ()
Value:
HAL_GPIO_WritePin(GPIOB, DIG1_Pin, GPIO_PIN_RESET)
Referenced by lcdTask_init().
DIG2_HIGH
#define DIG2_HIGH ()
Value:
HAL_GPIO_WritePin(GPIOB, DIG2_Pin, GPIO_PIN_SET)
Referenced by lcdTask_init().
DIG2_LOW
#define DIG2_LOW ()
Value:
HAL_GPIO_WritePin(GPIOB, DIG2_Pin, GPIO_PIN_RESET)
Referenced by lcdTask_init().
DP_OFF
#define DP_OFF ()
Value:
HAL_GPIO_WritePin(GPIOB, DP_Pin, GPIO_PIN_RESET)
Referenced by lcdTask_init().
DP_ON
#define DP_ON ()
Value:
HAL_GPIO_WritePin(GPIOB, DP_Pin, GPIO_PIN_SET)
Referenced by lcdTask_init().
Function Documentation
buzzerTask_init()
void buzzerTask_init (void * argument)
Buzzer control task.
Controls the buzzer behavior based on the measured distance. The buzzer toggles faster as the distance decreases.
Parameters
argument Pointer passed to the task (not used).
References Buzzer_Pin, Distance, and time.
Referenced by main().
lcdTask_init()
void lcdTask_init (void * argument)
7-segment display task.
LCD / 7-segment display handling task.
LCD display task.
Displays the shortest received distance on a multiplexed 2-digit 7-segment display. If the distance exceeds the maximum threshold, a warning pattern is shown.
Parameters
argument Pointer passed to the task (not used).
References DIG1_HIGH, DIG1_LOW, DIG2_HIGH, DIG2_LOW, digit1, digit2, Distance, DP_OFF, DP_ON, RxData, and SevenSegment_Update().
Referenced by main().
serialTask_init()
void serialTask_init (void * argument)
UART serial output task.
Serial communication task.
UART serial communication task.
Periodically transmits the measured distance value via UART for debugging or monitoring purposes.
Parameters
argument Pointer passed to the task (not used).
References Buffer, Distance, and huart2.
Referenced by main().
StartDefaultTask()
void StartDefaultTask (void * argument)
Default task handling LED indication logic.
Default FreeRTOS task.
This task selects the shortest distance received via CAN and updates LED patterns accordingly. It also updates the buzzer timing variable.
Parameters
argument Pointer passed to the task (not used).
References Distance, leds_1(), leds_2(), leds_3(), leds_4(), leds_5(), leds_6(), leds_7(), RxData, and time.
Referenced by main().
Variable Documentation
Buffer
char Buffer[8] extern
UART transmission buffer
Referenced by serialTask_init().
digit1
uint8_t digit1 extern
First displayed digit
Referenced by lcdTask_init().
digit2
uint8_t digit2 extern
Second displayed digit
Referenced by lcdTask_init().
Distance
float Distance extern
Distance value computed from received CAN data (meters)
Referenced by buzzerTask_init(), lcdTask_init(), serialTask_init(), and StartDefaultTask().
lcdBuffer
char lcdBuffer[8] extern
LCD/7-segment buffer
RxData
uint8_t RxData[8] extern
CAN received data buffer
Referenced by HAL_CAN_RxFifo0MsgPendingCallback(), lcdTask_init(), and StartDefaultTask().
time
int time extern
Buzzer timing variable (ms)
Referenced by buzzerTask_init(), and StartDefaultTask().