Reversing Radar Project: main.c File Reference
main.c File Reference
Functions
void SystemClock_Config (void)
System Clock Configuration.
static void MX_GPIO_Init (void)
GPIO Initialization Function.
static void MX_TIM1_Init (void)
TIM1 Initialization Function for input capture.
static void MX_TIM2_Init (void)
TIM2 Initialization Function for input capture.
static void MX_CAN_Init (void)
CAN Initialization Function.
static void MX_USART2_UART_Init (void)
USART2 Initialization Function.
int main (void)
Main program entry point.
void HAL_TIM_IC_CaptureCallback (TIM_HandleTypeDef *htim)
HAL Timer Input Capture callback.
void Error_Handler (void)
Error Handler.
Variables
TIM_HandleTypeDef htim1
External peripheral handles used in main.c.
TIM_HandleTypeDef htim2
CAN_HandleTypeDef hcan
UART_HandleTypeDef huart2
osThreadId_t us1TaskHandle
osThreadId_t us2TaskHandle
osThreadId_t TxTaskHandle
CAN_TxHeaderTypeDef TxHeader
CAN_FilterTypeDef canfilterconfig
uint32_t TxMailbox
uint8_t TxData [8]
uint8_t Distance_1 = 0
Distance measured by sensor 1 in cm.
uint8_t Distance_2 = 0
Distance measured by sensor 2 in cm.
Function Documentation
Error_Handler()
void Error_Handler (void)
Error Handler.
Handles unrecoverable application errors.
Handles HAL errors.
Referenced by MX_CAN_Init(), MX_TIM1_Init(), MX_TIM2_Init(), MX_USART2_UART_Init(), and SystemClock_Config().
HAL_TIM_IC_CaptureCallback()
void HAL_TIM_IC_CaptureCallback (TIM_HandleTypeDef * htim)
HAL Timer Input Capture callback.
Parameters
htim Pointer to the timer handle
Note
Forwarded to ultrasonic sensor module
References USensor_TIM_IC_Callback().
main()
int main (void)
Main program entry point.
Return values
int (not used, FreeRTOS scheduler takes over)
References hcan, htim1, htim2, MX_CAN_Init(), MX_GPIO_Init(), MX_TIM1_Init(), MX_TIM2_Init(), MX_USART2_UART_Init(), SystemClock_Config(), TxTask_init(), TxTaskHandle, us1Task_init(), us1TaskHandle, us2Task_init(), and us2TaskHandle.
MX_CAN_Init()
void MX_CAN_Init (void) static
CAN Initialization Function.
Configure CAN transmit header and filters
This block sets up the CAN message header for transmitting data and configures the filter to accept messages from the receiver node.
< Standard CAN frame
< Data frame
< Transmitter ID
< Filter bank index
< Accept messages from ID 0x104
< Mask to match ID 0x104
< ID mask mode
< 32-bit filter scale
< Only relevant for dual CAN controllers
< Apply filter configuration
References canfilterconfig, Error_Handler(), hcan, and TxHeader.
Referenced by main().
MX_GPIO_Init()
void MX_GPIO_Init (void) static
GPIO Initialization Function.
References TRIG1_Pin, and TRIG2_Pin.
Referenced by main().
MX_TIM1_Init()
void MX_TIM1_Init (void) static
TIM1 Initialization Function for input capture.
References Error_Handler(), and htim1.
Referenced by main().
MX_TIM2_Init()
void MX_TIM2_Init (void) static
TIM2 Initialization Function for input capture.
References Error_Handler(), and htim2.
Referenced by main().
MX_USART2_UART_Init()
void MX_USART2_UART_Init (void) static
USART2 Initialization Function.
References Error_Handler(), and huart2.
Referenced by main().
SystemClock_Config()
void SystemClock_Config (void)
System Clock Configuration.
Configures the system clock.
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Initializes the CPU, AHB and APB buses clocks
Referenced by main().
Variable Documentation
canfilterconfig
CAN_FilterTypeDef canfilterconfig
CAN filter config
Referenced by MX_CAN_Init(), and MX_CAN_Init().
Distance_1
uint8_t Distance_1 = 0
Distance measured by sensor 1 in cm.
Distance measured by sensor 1
Referenced by TxTask_init(), and USensor_TIM_IC_Callback().
Distance_2
uint8_t Distance_2 = 0
Distance measured by sensor 2 in cm.
Distance measured by sensor 2
Referenced by TxTask_init(), and USensor_TIM_IC_Callback().
hcan
CAN_HandleTypeDef hcan
CAN handle
htim1
TIM_HandleTypeDef htim1
External peripheral handles used in main.c.
Timer 1 handle
Referenced by main(), MX_TIM1_Init(), USensor_DelayUs(), USensor_Read1(), and USensor_TIM_IC_Callback().
htim2
TIM_HandleTypeDef htim2
Timer 2 handle
Referenced by main(), MX_TIM2_Init(), USensor_Read2(), and USensor_TIM_IC_Callback().
huart2
UART_HandleTypeDef huart2
UART2 handle
TxData
uint8_t TxData[8]
CAN transmit buffer
Referenced by TxTask_init().
TxHeader
CAN_TxHeaderTypeDef TxHeader
CAN transmit header
TxMailbox
uint32_t TxMailbox
CAN mailbox index
TxTaskHandle
osThreadId_t TxTaskHandle
CAN transmit task handle
Referenced by main().
us1TaskHandle
osThreadId_t us1TaskHandle
Ultrasonic sensor 1 task handle
Referenced by main().
us2TaskHandle
osThreadId_t us2TaskHandle
Ultrasonic sensor 2 task handle
Referenced by main().