Reversing Radar Project: app_tasks.c File Reference
app_tasks.c File Reference
Transmitter Node
FreeRTOS task implementations for the transmitter node.
Functions
void us1Task_init (void *argument)
RTOS thread to periodically read the first ultrasonic sensor.
void us2Task_init (void *argument)
RTOS thread to periodically read the second ultrasonic sensor.
void TxTask_init (void *argument)
RTOS thread to transmit sensor distances via CAN bus.
Detailed Description
FreeRTOS task implementations for the transmitter node.
This file contains the RTOS task loops responsible for:
Periodic ultrasonic sensor triggering (Sensor 1 and Sensor 2)
Packaging and transmitting distance measurements through CAN
Each task runs independently under FreeRTOS and uses modules provided in usensor.c and the CAN HAL driver.
Function Documentation
TxTask_init()
void TxTask_init (void * argument)
RTOS thread to transmit sensor distances via CAN bus.
Task for transmitting measured distances via CAN.
Task: TxTask_init
Parameters
argument Not used
autotoc_md2
Return values
None
< Unused parameter
< Fill CAN transmit buffer
< Transmit CAN message
< CAN transmission failed, signal with LED (optional)
< Wait 60 ms before next transmission
References Distance_1, Distance_2, hcan, TxData, TxHeader, and TxMailbox.
Referenced by main().
us1Task_init()
void us1Task_init (void * argument)
RTOS thread to periodically read the first ultrasonic sensor.
Task for first ultrasonic sensor reading.
Task: us1Task_init
Parameters
argument Not used
autotoc_md0
Return values
None
< Unused parameter
< Trigger first sensor measurement
< Wait minimum 60 ms between measurements
References USensor_Read1().
Referenced by main().
us2Task_init()
void us2Task_init (void * argument)
RTOS thread to periodically read the second ultrasonic sensor.
Task for second ultrasonic sensor reading.
Task: us2Task_init
Parameters
argument Not used
autotoc_md1
Return values
None
< Unused parameter
< Trigger second sensor measurement
< Wait minimum 60 ms between measurements
References USensor_Read2().
Referenced by main().