Reversing Radar Project: usensor.h File Reference
usensor.h File Reference
Transmitter Node
Ultrasonic sensor driver interface for STM32.
Macros
#define USENSOR1_TRIG_PIN TRIG1_Pin
Ultrasonic sensor 1 trigger pin.
#define USENSOR2_TRIG_PIN TRIG2_Pin
Ultrasonic sensor 2 trigger pin.
#define USENSOR_GPIO_PORT GPIOA
GPIO port for ultrasonic sensors.
Functions
void USensor_Init (void)
Initialize timers and GPIO for ultrasonic sensors.
void USensor_Read1 (void)
Trigger the first ultrasonic sensor.
void USensor_Read2 (void)
Trigger the second ultrasonic sensor.
void USensor_DelayUs (uint16_t us)
Delay for a specified number of microseconds.
void USensor_TIM_IC_Callback (TIM_HandleTypeDef *htim)
Callback function for Timer Input Capture events.
Variables
uint8_t Distance_1
Distance measured by sensor 1 in cm.
uint8_t Distance_2
Distance measured by sensor 2 in cm.
Detailed Description
Ultrasonic sensor driver interface for STM32.
This header provides:
Definitions of ultrasonic trigger pins
Access to measured distance variables
Function prototypes for sensor triggering and IC handling
The implementation relies on hardware timers configured in main.c.
Macro Definition Documentation
USENSOR1_TRIG_PIN
#define USENSOR1_TRIG_PIN TRIG1_Pin
Ultrasonic sensor 1 trigger pin.
Referenced by USensor_Read1().
USENSOR2_TRIG_PIN
#define USENSOR2_TRIG_PIN TRIG2_Pin
Ultrasonic sensor 2 trigger pin.
Referenced by USensor_Read2().
USENSOR_GPIO_PORT
#define USENSOR_GPIO_PORT GPIOA
GPIO port for ultrasonic sensors.
Referenced by USensor_Read1(), and USensor_Read2().
Function Documentation
USensor_DelayUs()
void USensor_DelayUs (uint16_t us)
Delay for a specified number of microseconds.
Parameters
us Number of microseconds to delay
Delay for a specified number of microseconds.
Parameters
us Number of microseconds to delay
References htim1.
Referenced by USensor_Read1(), and USensor_Read2().
USensor_Init()
void USensor_Init (void)
Initialize timers and GPIO for ultrasonic sensors.
USensor_Read1()
void USensor_Read1 (void)
Trigger the first ultrasonic sensor.
< 10us trigger pulse
References htim1, USENSOR1_TRIG_PIN, USensor_DelayUs(), and USENSOR_GPIO_PORT.
Referenced by us1Task_init().
USensor_Read2()
void USensor_Read2 (void)
Trigger the second ultrasonic sensor.
References htim2, USENSOR2_TRIG_PIN, USensor_DelayUs(), and USENSOR_GPIO_PORT.
Referenced by us2Task_init().
USensor_TIM_IC_Callback()
void USensor_TIM_IC_Callback (TIM_HandleTypeDef * htim)
Callback function for Timer Input Capture events.
Parameters
htim Pointer to the TIM handle
Callback function for Timer Input Capture events.
Parameters
htim Pointer to the TIM handle
Measures the pulse width for both ultrasonic sensors and calculates distance.
References Distance_1, Distance_2, htim1, htim2, IC1_Diff, IC1_FirstCaptured, IC1_Val1, IC1_Val2, IC2_Diff, IC2_FirstCaptured, IC2_Val1, and IC2_Val2.
Referenced by HAL_TIM_IC_CaptureCallback().
Variable Documentation
Distance_1
uint8_t Distance_1 extern
Distance measured by sensor 1 in cm.
Distance measured by sensor 1
Referenced by TxTask_init(), and USensor_TIM_IC_Callback().
Distance_2
uint8_t Distance_2 extern
Distance measured by sensor 2 in cm.
Distance measured by sensor 2
Referenced by TxTask_init(), and USensor_TIM_IC_Callback().