Reversing Radar Project: usensor.c File Reference
usensor.c File Reference
Transmitter Node
Ultrasonic sensor measurement driver using STM32 timers.
Functions
void USensor_DelayUs (uint16_t us)
Microsecond delay using TIM1.
void USensor_Read1 (void)
Trigger the first ultrasonic sensor.
void USensor_Read2 (void)
Trigger the second ultrasonic sensor.
void USensor_TIM_IC_Callback (TIM_HandleTypeDef *htim)
Input capture callback called from HAL_TIM_IC_CaptureCallback.
Variables
static uint32_t IC1_Val1 = 0
Internal variable for input capture of sensor 1.
static uint32_t IC1_Val2 = 0
Internal variable for input capture of sensor 1 (second reading).
static uint8_t IC1_FirstCaptured = 0
Flag to indicate first capture of sensor 1.
static uint32_t IC1_Diff = 0
Time difference captured for sensor 1.
static uint32_t IC2_Val1 = 0
Internal variable for input capture of sensor 2.
static uint32_t IC2_Val2 = 0
Internal variable for input capture of sensor 2 (second reading).
static uint8_t IC2_FirstCaptured = 0
Flag to indicate first capture of sensor 2.
static uint32_t IC2_Diff = 0
Time difference captured for sensor 2.
Detailed Description
Ultrasonic sensor measurement driver using STM32 timers.
This file implements:
Trigger generation for two ultrasonic sensors
Microsecond delay using a hardware timer
Input Capture processing for echo pulse measurement
The module converts echo pulse duration into a distance in centimeters and updates the global variables Distance_1 and Distance_2.
Function Documentation
USensor_DelayUs()
void USensor_DelayUs (uint16_t us)
Microsecond delay using TIM1.
Delay for a specified number of microseconds.
Parameters
us Number of microseconds to delay
References htim1.
Referenced by USensor_Read1(), and USensor_Read2().
USensor_Read1()
void USensor_Read1 (void)
Trigger the first ultrasonic sensor.
< 10us trigger pulse
References htim1, USENSOR1_TRIG_PIN, USensor_DelayUs(), and USENSOR_GPIO_PORT.
Referenced by us1Task_init().
USensor_Read2()
void USensor_Read2 (void)
Trigger the second ultrasonic sensor.
References htim2, USENSOR2_TRIG_PIN, USensor_DelayUs(), and USENSOR_GPIO_PORT.
Referenced by us2Task_init().
USensor_TIM_IC_Callback()
void USensor_TIM_IC_Callback (TIM_HandleTypeDef * htim)
Input capture callback called from HAL_TIM_IC_CaptureCallback.
Callback function for Timer Input Capture events.
Parameters
htim Pointer to the TIM handle
Measures the pulse width for both ultrasonic sensors and calculates distance.
References Distance_1, Distance_2, htim1, htim2, IC1_Diff, IC1_FirstCaptured, IC1_Val1, IC1_Val2, IC2_Diff, IC2_FirstCaptured, IC2_Val1, and IC2_Val2.
Referenced by HAL_TIM_IC_CaptureCallback().
Variable Documentation
IC1_Diff
uint32_t IC1_Diff = 0 static
Time difference captured for sensor 1.
Referenced by USensor_TIM_IC_Callback().
IC1_FirstCaptured
uint8_t IC1_FirstCaptured = 0 static
Flag to indicate first capture of sensor 1.
Referenced by USensor_TIM_IC_Callback().
IC1_Val1
uint32_t IC1_Val1 = 0 static
Internal variable for input capture of sensor 1.
Referenced by USensor_TIM_IC_Callback().
IC1_Val2
uint32_t IC1_Val2 = 0 static
Internal variable for input capture of sensor 1 (second reading).
Referenced by USensor_TIM_IC_Callback().
IC2_Diff
uint32_t IC2_Diff = 0 static
Time difference captured for sensor 2.
Referenced by USensor_TIM_IC_Callback().
IC2_FirstCaptured
uint8_t IC2_FirstCaptured = 0 static
Flag to indicate first capture of sensor 2.
Referenced by USensor_TIM_IC_Callback().
IC2_Val1
uint32_t IC2_Val1 = 0 static
Internal variable for input capture of sensor 2.
Referenced by USensor_TIM_IC_Callback().
IC2_Val2
uint32_t IC2_Val2 = 0 static
Internal variable for input capture of sensor 2 (second reading).
Referenced by USensor_TIM_IC_Callback().