/**
 * @file    main.h
 * @ingroup Transmitter_Node
 * @brief   Header file for the main application of the STM32 transmitter node.
 *
 * This file provides:
 *   - Core system includes
 *   - Global peripheral handle declarations
 *   - GPIO pin definitions
 *   - Prototypes for system configuration and initialization functions
 *
 * It is included by all modules requiring access to global peripherals
 * such as timers, CAN, and UART, as well as shared GPIO definitions.
 *
 * @note    Peripheral initialization functions declared here are implemented
 *          in main.c and should not be modified unless hardware changes.
 */
#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32f1xx_hal.h"

/* ---------------------- Pin Definitions ---------------------- */
/**
 * @brief Trigger pins for Ultrasonic sensors
 */
#define TRIG1_Pin      GPIO_PIN_9
#define TRIG1_GPIO_Port GPIOA
#define TRIG2_Pin      GPIO_PIN_12
#define TRIG2_GPIO_Port GPIOA

/* ---------------------- Peripheral Handles ---------------------- */
/**
 * @brief External peripheral handles used in main.c
 */
extern TIM_HandleTypeDef htim1;   /**< Timer 1 handle */
extern TIM_HandleTypeDef htim2;   /**< Timer 2 handle */
extern CAN_HandleTypeDef hcan;    /**< CAN handle */
extern UART_HandleTypeDef huart2; /**< UART2 handle */

/* ---------------------- Function Prototypes ---------------------- */
/**
 * @brief  Configures the system clock
 * @note   Generated by CubeMX or manually implemented in main.c
 */
void SystemClock_Config(void);

/**
 * @brief  Handles HAL errors
 * @note   Typically halts the system when an unrecoverable error occurs
 */
void Error_Handler(void);

/* Peripheral initialization functions generated by CubeMX */
static void MX_GPIO_Init(void);
static void MX_TIM1_Init(void);
static void MX_TIM2_Init(void);
static void MX_CAN_Init(void);
static void MX_USART2_UART_Init(void);

#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H */
